name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s '/Applications/Xcode_11.5.app/Contents/Developer'

    - name: Cache Carthage
      uses: actions/cache@v2
      id: cache-carthage
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-

    - name: Carthage
      if: steps.cache-carthage.outputs.cache-hit != 'true'
      run: carthage bootstrap --platform iOS --no-use-binaries --cache-builds

    - name: Build
      run: xcodebuild -scheme RxCoreNFC -sdk iphonesimulator -configuration Debug build
